#!/usr/bin/env bash
# Regenerates assets/sa-manifest.js by reading the curated CATALOG below (titles,
# group, and the "what's on it" blurb come from the intended artwork, not the
# filename). Add a row when you plan/drop in a new sheet. Run from
# printables/supplemental_aids_math/.
#
# Unlike the science builder, this one emits a row for every CATALOG entry even
# before its PNG exists, so the gallery page is fully wired while you generate the
# images with Codex (missing PNGs simply 404 until produced). It notes which are
# still missing. .pdf and _packet.pdf links are added only once those files exist.
set -euo pipefail
cd "$(dirname "$0")"

# base|group|title|blurb
# The gallery groups sheets under the headings below, in this order. Each group
# after "Start here"/"Reference" leads with its concept cards.
read -r -d '' CATALOG <<'ROWS' || true
ma_overview|Start here|Middle School Math — Overview|A one-page map of the collection: the math strands and the cue cards inside each.
ma_formula_reference|Reference|Measurement Formula Reference|Perimeter, area, circumference, volume, and surface-area formulas — the shapes tested in grades 6–8, one page.
ma_integer_operations|Number & Operations|Integer Operation Rules|Signs for adding, subtracting, multiplying, and dividing positive and negative numbers — same/different sign cues.
ma_order_of_operations|Number & Operations|Order of Operations (GEMDAS)|Grouping, exponents, multiply/divide left to right, then add/subtract left to right — with a worked example.
ma_fraction_operations|Number & Operations|Fraction Operations|Add and subtract with a common denominator; multiply across; divide by multiplying by the reciprocal (KCF).
ma_fraction_decimal_percent|Number & Operations|Fractions, Decimals & Percents|Convert among the three forms — the triangle of "out of 100," divide to a decimal, and move the decimal two places.
ma_ratios_unit_rate|Proportionality|Ratios & Unit Rate|Compare quantities three ways (a to b, a:b, a/b) and find the unit rate by dividing to get "per one."
ma_proportions|Proportionality|Proportions & Cross Products|Set two equal ratios, then cross-multiply and solve for the missing value — a scaling picture.
ma_percent_applications|Proportionality|Percent Applications|Percent of a number, percent change, and tax/tip/discount — part = percent × whole, and the percent bar model.
ma_combining_like_terms|Expressions, Equations & Relationships|Expressions: Like Terms & Distributive|Combine like terms (same variable and exponent) and distribute a factor across a sum — a(b + c) = ab + ac.
ma_one_two_step_equations|Expressions, Equations & Relationships|Solving One- & Two-Step Equations|Undo operations with inverses to isolate the variable, keeping the equation balanced on both sides.
ma_inequalities|Expressions, Equations & Relationships|Solving & Graphing Inequalities|Solve like an equation, flip the sign when multiplying/dividing by a negative, and graph open vs. closed circles.
ma_coordinate_plane|Expressions, Equations & Relationships|The Coordinate Plane|The four quadrants, x- and y-axes, the origin, and how to plot an ordered pair (x, y) — over then up/down.
ma_slope_linear|Expressions, Equations & Relationships|Slope & Linear Relationships|Slope as rise over run, the slope triangle, and y = mx + b — what m and b do to a line.
ma_measures_of_center|Data & Statistics|Mean, Median, Mode & Range|The four one-word cues — mean (average), median (middle), mode (most), range (spread) — with a small data set.
ma_probability|Data & Statistics|Simple Probability|Probability = favorable ÷ total, the 0-to-1 (impossible-to-certain) scale, and experimental vs. theoretical.
ROWS

esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

out=assets/sa-manifest.js
n=0; missing=0
{
  echo "/* AUTO-GENERATED by build-manifest.sh — do not edit by hand. */"
  echo "window.MA_MANIFEST = ["
  while IFS='|' read -r base group title blurb; do
    [ -n "$base" ] || continue
    png="${base}.png"
    [ -f "$png" ] || { echo "NOTE: $png not generated yet (row skipped)." >&2; missing=$((missing+1)); continue; }
    pdf="${base}.pdf";        pdfval="";    [ -f "$pdf" ]    && pdfval="$pdf"
    packet="${base}_packet.pdf"; packetval=""; [ -f "$packet" ] && packetval="$packet"
    printf '  { "strand": "%s", "title": "%s", "blurb": "%s", "file": "%s", "pdf": "%s", "packet": "%s" },\n' \
      "$(esc "$group")" "$(esc "$title")" "$(esc "$blurb")" "$png" "$pdfval" "$packetval"
    n=$((n+1))
  done <<< "$CATALOG"
  echo "];"
} > "$out"

# Flag any PNG on disk that is missing from the CATALOG.
for png in ma_*.png; do
  [ -e "$png" ] || continue
  base="${png%.png}"
  grep -q "^${base}|" <<< "$CATALOG" || echo "NOTE: $png is on disk but not in CATALOG (add a row)." >&2
done

echo "Wrote $out ($n entries, $missing image(s) not yet generated)"
