#!/usr/bin/env bash
# Regenerates assets/sa-manifest.js by scanning the Supplemental Aids PNGs in this
# folder. Titles, the TEKS strand, and the "what's on it" blurb are curated here
# (they come from the artwork, not the filename), so add a row to CATALOG when you
# drop in a new sheet. Run from printables/supplemental_aids/.
set -euo pipefail
cd "$(dirname "$0")"

# base|strand|title|blurb
# order below is also the gallery display order.
read -r -d '' CATALOG <<'ROWS' || true
sa_overview|Overview|Middle School Science — All Four Strands|A one-page map of the collection: the four science strands and the cue cards inside each.
sa_matter_and_energy|Matter & Energy|Matter and Energy|States of matter, evidence of chemical change (GTPC), physical vs. chemical change, particle motion, and conservation of mass.
sa_force_motion_energy|Force, Motion & Energy|Force, Motion, and Energy|Average-speed and force formula triangles, Newton's three laws, heat transfer, and wave properties.
sa_earth_and_space|Earth & Space|Earth and Space|Plate boundaries, rock layers and fossils, weather systems, the star life cycle, and galaxy types.
sa_organisms_environments|Organisms & Environments|Organisms and Environments|Plant and animal cells, cell structures, photosynthesis, ecological succession, and food chains and webs.
ROWS

esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

out=assets/sa-manifest.js
n=0
{
  echo "/* AUTO-GENERATED by build-manifest.sh — do not edit by hand. */"
  echo "window.SA_MANIFEST = ["
  while IFS='|' read -r base strand title blurb; do
    [ -n "$base" ] || continue
    png="${base}.png"
    if [ ! -f "$png" ]; then
      echo "  WARNING: $png listed in CATALOG but not found on disk" >&2
      continue
    fi
    pdf="${base}.pdf"
    pdfval=""
    [ -f "$pdf" ] && pdfval="$pdf"
    printf '  { "strand": "%s", "title": "%s", "blurb": "%s", "file": "%s", "pdf": "%s" },\n' \
      "$(esc "$strand")" "$(esc "$title")" "$(esc "$blurb")" "$png" "$pdfval"
    n=$((n+1))
  done <<< "$CATALOG"
  echo "];"
} > "$out"

# Flag any PNG on disk that is missing from the CATALOG.
for png in sa_*.png; do
  [ -e "$png" ] || continue
  base="${png%.png}"
  grep -q "^${base}|" <<< "$CATALOG" || echo "NOTE: $png is on disk but not in CATALOG (add a row)." >&2
done

echo "Wrote $out ($n entries)"
