#!/usr/bin/env bash
# Regenerates assets/srf-manifest.js by scanning the Student Refusal Form PNGs in
# this folder. Titles and categories are curated here (they come from the artwork,
# not the filename), so add a row to CATALOG when you drop in a new form.
# Run from tgt/srf/.
set -euo pipefail
cd "$(dirname "$0")"

# base|category|subject|title      (subject is "" for non content-area forms)
# category order below is also the gallery display order.
read -r -d '' CATALOG <<'ROWS' || true
srf_gen_404|tech||404: Assignment Not Found
srf_gen_low_battery|tech||Low Battery
srf_gen_loading|tech||Loading… Better Choices
srf_gen_howitstarted_going|social||How It Started vs. How It's Going
srf_gen_listendontjudge|social||We Listen and We Don't Judge
srf_gen_nothoughts_justvibes|social||No Thoughts, Just Vibes
srf_gen_otherplans|social||I Had Other Plans
srf_gen_plottwist|social||Plot Twist: The Work Still Has to Get Done
srf_gen_tell_me_you_didnt|social||Tell Me You Didn't Do the Work…
srf_gen_experiment|games||Experiment Report: Results Incomplete
srf_gen_game_day|games||Game Day: Make the Play
srf_gen_getitdone|games||Mission: Get It Done
srf_science|content|Science|This Is Fine? (Science)
srf_math|content|Mathematics|Task Failed Successfully (Math)
srf_ela|content|ELA|Me vs. The Assignment (ELA)
srf_reading|content|Reading|Nobody… Me: Not Doing the Assignment (Reading)
srf_ss|content|Social Studies|Well, Well, Well… If It Isn't the Consequences (Social Studies)
srf_art|content|Art|POV: You Had 30 Minutes (Art)
srf_music|content|Music|My Brain Had Other Plans (Music)
srf_pe|content|PE|Surprised Student Moment (PE)
srf_tech|content|Technology|Choose Your Fighter (Technology)
srf_worldlanguages|content|World Languages|Achievement Unlocked (World Languages)
ROWS

esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

out=assets/srf-manifest.js
n=0
{
  echo "/* AUTO-GENERATED by build-manifest.sh — do not edit by hand. */"
  echo "window.SRF_MANIFEST = ["
  while IFS='|' read -r base category subject title; do
    [ -n "$base" ] || continue
    png="${base}.png"
    if [ ! -f "$png" ]; then
      echo "  WARNING: $png listed in CATALOG but not found on disk" >&2
      continue
    fi
    pdf="${base}.pdf"
    pdfval=""
    [ -f "$pdf" ] && pdfval="$pdf"
    printf '  { "category": "%s", "subject": "%s", "title": "%s", "file": "%s", "pdf": "%s" },\n' \
      "$(esc "$category")" "$(esc "$subject")" "$(esc "$title")" "$png" "$pdfval"
    n=$((n+1))
  done <<< "$CATALOG"
  echo "];"
} > "$out"

# Flag any PNG on disk that is missing from the CATALOG.
for png in srf_*.png; do
  [ -e "$png" ] || continue
  base="${png%.png}"
  grep -q "^${base}|" <<< "$CATALOG" || echo "NOTE: $png is on disk but not in CATALOG (add a row)." >&2
done

echo "Wrote $out ($n entries)"
