from pathlib import Path
from html import escape
ROOT=Path(__file__).parent
pages=[]
def page(title, audience, content): pages.append((title,audience,content))
page('Launch literature circles','TEACHER • QUICK START', '''
<p class="lead">Grades 5–12 · Small groups, shared reading, student-led meaning making.</p>
<div class="callout"><b>Start tomorrow:</b> Clear the practice text (p. 2), copy pp. 5–9, form groups of four, and run the 45-minute launch on p. 4. No devices or purchased books are required for the practice lesson.</div>
<h2>What makes it a literature circle?</h2><p>Students read a common text within their group, bring their own questions, and build interpretations together. Offer choices from locally approved readings when possible. Different groups may read different texts, or the same text. Roles support conversation; everyone reads and interprets the whole assigned section.</p>
<h2>Before students arrive</h2><ul><li>Choose one reading goal and its TEKS (p. 3). Example: explain how choices reveal a theme, using two details.</li><li>Provide one text per reader, pencils, timer, group folder, and accessible versions. Print teacher pp. 1–4 and 10 once; pp. 5 and 8 once per group; pp. 6, 7, and 9 once per student.</li><li>Group 3–5 readers by interest and access needs. Avoid permanent ability labels. Seat groups so everyone can see one another; reserve a conference spot.</li><li>Set reading chunks at meaningful breaks, meeting dates, in-class reading time, and an absence plan. Check access before assigning home reading.</li><li>Model a short discussion, then collect each student's own response. Coach groups while students lead.</li></ul>
<h2>Your 10-page toolkit</h2><table><tr><th>Teacher pages</th><th>Student and group copies</th></tr><tr><td>1 Launch checklist<br>2 Text selection and approval<br>3 TEKS planning map<br>4 Schedule and facilitation<br>10 Assessment, troubleshooting, sources</td><td>5 Group agreement and reading calendar<br>6 Individual reading preparation<br>7 Rotating roles and talk moves<br>8 Meeting agenda and record<br>9 Practice reading and independent response</td></tr></table>
<h2>Make learning visible</h2><p><b>Learning intention:</b> We are learning to build and revise interpretations together. <b>Success criteria:</b> I bring a question, explain relevant text evidence, respond to a peer, and identify how my thinking changed. Share these before every meeting; use p. 10 to give one specific next step.</p>
''')
page('Choose and clear the reading','TEACHER • TEXT APPROVAL', '''
<div class="callout"><b>Approval is local.</b> The suggestions below are candidates, not a Texas-approved title list. Use your school/district's current selection process, curriculum list, and required family notification. Public-domain status does not establish instructional approval.</div>
<h2>Screen the exact edition or excerpt</h2><p>Read the selection fully. Check developmental fit, complexity, cultural context, stereotypes or dated language, sensitive content, curriculum purpose, and discussion potential. Confirm legal copies and accessibility for every reader. Record any required approval and an equivalent alternate reading before offering choices. Consult your librarian or curriculum lead when status is uncertain.</p>
<table><tr><th>Candidate / suggested band</th><th>Why consider it / preview first</th></tr>
<tr><td>Aesop, “The North Wind and the Sun”<br>5–12: launch practice</td><td>Short, low-barrier fable; choices, power, persuasion. Older readers critique the moral and whose viewpoint is missing. Retelling on p. 9.</td></tr>
<tr><td>Frances Hodgson Burnett, <i>The Secret Garden</i> (1911)<br>5–7: selected chapters or novel</td><td>Character change and belonging; preview colonial attitudes, racist language, disability portrayal, and death.</td></tr>
<tr><td>Louisa May Alcott, <i>Little Women</i> (1868–69)<br>7–9: selected chapters or novel</td><td>Family, ambition, conflict; preview gender expectations, religious references, illness, and death.</td></tr>
<tr><td>O. Henry, “The Gift of the Magi” (1905)<br>7–10: short story</td><td>Irony and sacrifice; preview dated vocabulary, poverty, and Christmas context.</td></tr>
<tr><td>Frederick Douglass, <i>Narrative of the Life of Frederick Douglass</i> (1845)<br>9–12: selected chapters</td><td>Literacy, voice, and freedom; plan context and support for accounts of enslavement, violence, and racist language.</td></tr></table>
<p class="small">Original works above are public domain in the United States; modern translations, introductions, illustrations, and annotations may have separate rights. These bands are starting points for teacher review, not reading-level guarantees. A locally approved contemporary text or nonfiction reading may replace any candidate.</p>
<h2>Our locally approved menu — complete before launch</h2><table class="write"><tr><th>Title / author / edition / section</th><th>Approval source, reviewer, date</th><th>Copies, access, alternate</th></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr></table>
<p>Instructional purpose / family communication required and completed: _____________________<br>____________________________________________________________________________</p>
''')
page('Plan from the TEKS','TEACHER • TEXAS ELAR', '''
<p>Use the row for the enrolled grade/course, select a narrow target, and collect the evidence shown below. Codes refer to subsection (b) of the cited rule. Descriptions are planning paraphrases. A discussion format alone does not demonstrate mastery.</p>
<table><tr><th>Grade / rule</th><th>Collaboration</th><th>Comprehension / response</th><th>Literary focus</th></tr>
<tr><td>5 · §110.7</td><td>1(D): shared responsibilities</td><td>6(B,F,I): questions, inference, monitoring; 7(C,D): evidence, summary</td><td>8(A): multiple themes within a text</td></tr>
<tr><td>6 · §110.22</td><td>1(D): student-led talk, notes, agreement/disagreement</td><td>5(B,F,I); 6(C,D): questions, inference, monitoring, evidence, summary</td><td>7(A): multiple themes within/across texts</td></tr>
<tr><td>7 · §110.23</td><td>1(D): meaningful discourse; constructive feedback</td><td>5(B,F,I); 6(C,D): same focus areas as grade 6</td><td>7(A): multiple themes within/across texts</td></tr>
<tr><td>8 · §110.24</td><td>1(D): agendas, goals, deadlines, roles</td><td>5(B,F,I); 6(C,D): same focus areas as grade 6</td><td>7(A): theme through characters/events</td></tr>
<tr><td>English I · §110.36</td><td>1(D): build on ideas and reach decisions</td><td>4(B,F,I); 5(C,D): questions, inference, monitoring, commentary, summary</td><td>6(A): theme through characterization/plot</td></tr>
<tr><td>English II · §110.37</td><td>1(D): build on ideas and reach decisions</td><td>4(B,F,I); 5(C,D): interpretive commentary and summary</td><td>6(A): theme; cross-cultural comparison</td></tr>
<tr><td>English III · §110.38</td><td>1(D): purposeful ideas; evaluate teamwork</td><td>4(B,F,I); 5(C,D): analytic commentary and summary</td><td>6(A): relationships among literary elements</td></tr>
<tr><td>English IV · §110.39</td><td>1(D): purposeful ideas; evaluate teamwork</td><td>4(B,F,I); 5(C,D): evaluative commentary and summary</td><td>6(A): relationships among literary elements</td></tr></table>
<h2>Match the target to observable evidence</h2><ul><li><b>Collaboration:</b> p. 5 responsibilities + p. 8 agenda; teacher records a student's response to a peer.</li><li><b>Comprehension:</b> p. 6 question, supported inference, and repair strategy; predictions must be revisited.</li><li><b>Response:</b> p. 9 individual claim, evidence, and explanation; p. 8 accurate group summary.</li><li><b>Literary analysis:</b> extend p. 9 using the chosen grade/course focus. Add a second approved text for an across-text target; a single fable cannot meet every listed expectation.</li></ul>
<p><b>For nonfiction:</b> retain collaboration/comprehension/response targets; replace the literary focus with your course's informational or argumentative-text expectation. High school alignment follows course enrollment, not grade number alone.</p>
<p>My target code: __________________ Learning intention: _____________________________<br>Evidence I will collect: __________________________________________________________</p>
<p class="small">Verified September 16, 2026 against TEA Chapter 110, Subchapters A–C. Official links and research sources are on p. 10.</p>
''')
page('Run the launch and the cycle','TEACHER • FACILITATION', '''
<h2>First meeting: 45 minutes with the p. 9 fable</h2><table><tr><th>Time</th><th>Teacher and student actions</th></tr><tr><td>0–5</td><td>State the goal and success criteria (p. 1). Explain norms and show a text-supported response.</td></tr><tr><td>5–12</td><td>Read p. 9; pause before paragraph 3 to predict. Students reread and begin p. 6.</td></tr><tr><td>12–18</td><td>Model question → clarification → evidence → summary. Think aloud about revising a prediction. Invite two students to respond.</td></tr><tr><td>18–23</td><td>Groups complete p. 5 and assign p. 7 roles. Each student prepares a question and evidence.</td></tr><tr><td>23–40</td><td>Students run p. 8's 17-minute agenda. Visit two groups; note evidence and coach one talk move.</td></tr><tr><td>40–45</td><td>Each student completes p. 9's exit response. Give a next step and set the next reading deadline.</td></tr></table>
<h2>Reusable two-week cycle: five 45-minute lessons</h2><p><b>1:</b> Model and practice; offer the locally approved menu and form groups. <b>2:</b> Read chunk 1 in class (20 min), prepare (8), meet (17). <b>3:</b> Repeat for chunk 2; conference with different groups. <b>4:</b> Repeat for chunk 3; use optional Jigsaw only when helpful. <b>5:</b> Finish reading, meet, write an individual synthesis, and reflect. For novels, repeat lessons 2–4 until the text is finished; enter actual dates and sections on p. 5.</p>
<h2>Reciprocal Teaching: a comprehension scaffold</h2><p>Explicitly model <b>predicting, questioning, clarifying, and summarizing</b>; guide practice, then transfer leadership. Rotate leadership at a section break or next meeting. Each student uses all four strategies on p. 6; p. 7 assigns who starts each move. Predict before reading the next section, then confirm or revise. Use clarification when meaning breaks down. Let students' questions drive interpretation after the comprehension check.</p>
<h2>Optional Jigsaw: deepen, then return to the circle</h2><p>Use only after everyone has read the same selection and groups can talk productively. Assign each home-group member a lens: character choices, language, plot, or theme. Meet in same-lens expert groups (6 min); find two details and agree on an explanation. Teacher checks accuracy. Return home (8 min); each expert teaches while peers question and record evidence. Each student writes how two lenses connect (3 min). Substitute this 17-minute block for one meeting. With three readers combine plot/theme; with five add point of view.</p>
<div class="callout">Jigsaw should enrich shared reading. Avoid dividing unread novel chapters among experts: every reader needs the story context. Fade role sheets as students independently use the strategies; keep preparation and individual evidence.</div>
''')
page('Our circle agreement and calendar','GROUP HANDOUT • KEEP IN FOLDER', '''
<p>Group: __________________________ Class / period: __________ Date: ______________<br>Text / author / edition: __________________________________________________________<br>Our learning goal: _____________________________________________________________</p>
<h2>Agree before you begin</h2><p>Check each agreement together. Add one norm your group needs.</p><ul class="checks"><li>☐ We read the whole assigned section and bring p. 6, our text, and a pencil.</li><li>☐ We invite every member, allow thinking time, and listen without interrupting.</li><li>☐ We discuss the text and ideas respectfully. Nobody must share personal experiences.</li><li>☐ We give page/paragraph evidence and consider more than one interpretation.</li><li>☐ We stay within the assigned section to avoid spoilers and finish with a next step.</li><li>☐ We ask the teacher for help when our agreed repair steps do not work.</li></ul>
<p>Our added norm: ______________________________________________________________</p>
<h2>Members and first meeting jobs</h2><table class="write"><tr><th>Member</th><th>First job (p. 7)</th><th>Access/support needed (optional)</th></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr></table>
<h2>Reading and meeting calendar — confirm with teacher</h2><table class="write"><tr><th>Meeting date</th><th>Read through (chapter/pages/paragraphs)</th><th>In-class reading time / next leader</th></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr><tr><td></td><td></td><td></td></tr></table>
<h2>If someone is absent or behind</h2><p>The folder stays at: ____________________ Our catch-up time is: ____________________<br>The teacher provides the reading and notes. A returning reader reviews p. 8 and prepares a question. A reader who is behind uses a short reread with support before joining; peers do not complete that reader's work. Reassign an absent member's job temporarily.</p>
<p>We agree (initials): __________________________ Teacher check: ____________________</p>
''')
page('Read, prepare, and bring evidence','INDIVIDUAL HANDOUT • COPY EACH CYCLE', '''
<p>Name: __________________________ Group: __________ Meeting date: ______________<br>Text / assigned section: _________________________________________________________</p>
<div class="callout"><b>Everyone prepares.</b> Read the entire assigned section. Write brief notes below; your job does not limit your thinking. Use chapter/page or paragraph numbers from your edition.</div>
<h2>1 · Predict, then revisit</h2><p>Before reading or at a stopping point: What might happen or develop? What clue supports it?</p><div class="lines two"></div><p>After reading: My prediction was confirmed / revised because…</p><div class="lines two"></div>
<h2>2 · Ask an open question</h2><p>Ask about a choice, conflict, idea, or author's craft. It should invite explanation and allow more than one reasonable interpretation. “Why might…?” or “How does…?”</p><div class="lines two"></div>
<h2>3 · Clarify a difficulty</h2><p>Confusing word, passage, or idea + location: _________________________________________<br>Repair used: ☐ reread ☐ context clues ☐ glossary/resource ☐ ask for help<br>Now I understand… / I still need help with…</p><div class="lines two"></div>
<h2>4 · Summarize the essentials</h2><p>In 2–3 sentences, explain the key events or ideas accurately and in order. Keep your opinion separate.</p><div class="lines three"></div>
<h2>5 · Bring two details and an interpretation</h2><table class="write"><tr><th>Location + short quotation or accurate paraphrase</th><th>What it suggests / why it matters</th></tr><tr><td></td><td></td></tr><tr><td></td><td></td></tr></table>
<p>My first idea about the theme, central idea, or author's choice: __________________________<br>____________________________________________________________________________</p>
<p class="small">Ready check: ☐ Reading completed ☐ Question ready ☐ Evidence located ☐ Support requested if needed</p>
''')
page('Rotate leadership; share the thinking','STUDENT HANDOUT • ROLE AND TALK GUIDE', '''
<p>Assign who starts each move. Everyone may question, clarify, summarize, predict, and interpret. Rotate jobs one position each meeting. With three members combine Summarizer and Predictor; with five add an Evidence Tracker to note locations on p. 8.</p>
<table><tr><th>Job</th><th>What to do</th><th>Try saying…</th></tr><tr><td><b>Questioner / facilitator</b></td><td>Open with the learning goal. Invite each reader's question; help select one worth exploring. Invite quieter voices and watch time.</td><td>“Which question will help us understand this section?”<br>“Would you like to add, read your note, or pass for now?”</td></tr><tr><td><b>Clarifier</b></td><td>Invite difficulties. Lead a reread; use context or a resource. Check whether the explanation fits the passage.</td><td>“Where did meaning break down?”<br>“Let's reread before and after that line.”</td></tr><tr><td><b>Summarizer / recorder</b></td><td>Give a brief accurate section summary. After discussion, record the group's interpretation, evidence, disagreement, and next step on p. 8.</td><td>“The essential events or ideas are…”<br>“We agree on… but still differ about…”</td></tr><tr><td><b>Predictor / timekeeper</b></td><td>Revisit earlier predictions. Use a clue to predict the next section before reading it. Announce agenda transitions and confirm the deadline.</td><td>“Our earlier prediction changed because…”<br>“This clue makes me expect…”</td></tr></table>
<h2>Talk moves that build an interpretation</h2><ul><li><b>Locate:</b> “In paragraph/page ___, the text says/shows…”</li><li><b>Explain:</b> “That matters because…”</li><li><b>Build:</b> “Adding to your idea, another detail is…”</li><li><b>Test:</b> “Does that explanation fit this other passage?”</li><li><b>Disagree respectfully:</b> “I read it differently because…”</li><li><b>Revise:</b> “I first thought… Now I think… because…”</li></ul>
<h2>When the conversation stalls</h2><p>Pause for 30 seconds of writing. Reread one short passage. Invite a question from each reader. Choose one question and compare two possible answers using the text. If disagreement continues, record both supported views; you do not have to force consensus.</p>
<div class="callout"><b>Roles are temporary scaffolds.</b> When your group uses these moves without reminders, ask the teacher to use a shared agenda instead of assigned roles. Keep the same reading and evidence expectations.</div>
<p>My job this meeting: __________________ Next meeting: ____________________________<br>One talk move I will practice: ___________________________________________________</p>
''')
page('Meeting agenda and group record','GROUP HANDOUT • COPY EACH MEETING', '''
<p>Group: ____________________ Date: __________ Text / section: _____________________<br>Present: ___________________________ Absent / temporary job changes: ______________<br>Today's learning goal: __________________________________________________________</p>
<h2>Follow this 17-minute agenda</h2><table><tr><th>Minutes</th><th>Action</th></tr><tr><td>0–2</td><td>Check materials and goal. Give the short summary; revisit an earlier prediction.</td></tr><tr><td>2–5</td><td>Invite every reader's question or difficulty. Clarify by rereading and select a focus question.</td></tr><tr><td>5–12</td><td>Explore that question. Each reader contributes evidence or responds to a peer; compare interpretations. Include anyone who passed earlier.</td></tr><tr><td>12–15</td><td>Record a supported interpretation and an unresolved question. Predict the next section if there is one; otherwise identify a new question.</td></tr><tr><td>15–17</td><td>Self-check; set reading deadline and rotate jobs. Return the folder; write the individual exit response as directed.</td></tr></table>
<h2>Our focus question</h2><div class="lines two"></div>
<h2>What we now think and what supports it</h2><table class="write"><tr><th>Interpretation / explanation</th><th>Two text locations and supporting details</th></tr><tr class="tall"><td></td><td></td></tr></table>
<p>A different supported view or unresolved question:</p><div class="lines two"></div>
<h2>Participation and next steps</h2><p>Members who contributed evidence or responded to an idea (initials): ___________________<br>How we invited others / support we need: __________________________________________<br>Next prediction + clue OR new question: ____________________________________________<br>Read through: __________________ Due: __________ Next job rotation: ________________</p>
<p>Group check: ☐ We used evidence ☐ We considered another view ☐ We know our next step<br>One improvement for next time: __________________________________________________</p>
<p class="small">This record supports reflection. The teacher assesses each student's understanding using individual work and observation.</p>
''')
page('Practice with a public-domain fable','STUDENT HANDOUT • READING AND EXIT RESPONSE', '''
<p>Name: ______________________________ Date: __________ Group: _________________</p>
<h2>The North Wind and the Sun</h2><p class="small">An original classroom retelling of Aesop's public-domain fable, based on <i>The Aesop for Children</i> (1919). Paragraph numbers support evidence citations. This is an adaptation, not a quotation of the historical edition.</p>
<div class="reading"><p><b>1.</b> The North Wind and the Sun argued about which of them was stronger. As they argued, a traveler appeared on the road, wrapped in a cloak. They agreed on a test: whoever could make the traveler remove the cloak would win.</p><p><b>2.</b> The North Wind went first. He blew a cold blast toward the traveler. The traveler pulled the cloak tightly around his body. The Wind blew harder and harder, but each gust made the traveler hold on more firmly. At last the Wind stopped.</p><p><b>Pause:</b> What might the Sun do? Write a prediction and clue on p. 6 before continuing.</p><p><b>3.</b> The Sun began to shine gently. The traveler loosened the cloak as the air grew warmer. Then the Sun shone more brightly. Feeling hot, the traveler took off the cloak. The Sun had won the test.</p></div>
<p><b>Vocabulary:</b> cloak = loose outer garment; gust = sudden strong rush of wind.<br><b>Discussion invitation:</b> What does this contest suggest about influence? Does winning this test prove who is stronger?</p>
<h2>Choose the teacher-assigned challenge</h2><p><b>Grades 5–6:</b> Compare the characters' actions; propose two possible lessons supported by details. <b>7–8:</b> Explain how the sequence of events develops a theme and test another interpretation. <b>9–10:</b> Analyze characterization and contrast; question the contest's definition of strength. <b>11–12:</b> Evaluate how viewpoint, plot, and characterization shape the message; consider the traveler's missing perspective. The fable is practice; transfer to a sufficiently complex approved text.</p>
<h2>Independent exit response — after discussion</h2><p>Make a claim answering your challenge. Use two paragraph references and explain how each detail supports your claim. Include an alternative interpretation or a limitation when appropriate.</p><div class="lines four"></div>
<p>My thinking changed / became clearer because… (identify a peer idea or passage)</p><div class="lines two"></div>
<p>Self-check: ☐ Clear claim ☐ Two details + locations ☐ Explanation ☐ Reflection<br>My next step: __________________________________________________________________</p>
''')
page('Assess, adjust, and keep going','TEACHER • FEEDBACK AND SOURCES', '''
<h2>Use a brief individual evidence check</h2><p>Use pp. 6 and 9 plus your observations. For each dimension mark <b>2 = independent and accurate; 1 = partial or needs prompting; 0 = not yet shown.</b> Reassess after feedback. Adapt scoring to local policy; do not substitute a group score for individual understanding.</p>
<table><tr><th>Dimension</th><th>Evidence for a 2</th></tr><tr><td>Preparation / comprehension</td><td>Accurate summary, meaningful question, and a useful clarification or prediction revision.</td></tr><tr><td>Interpretation / evidence</td><td>Defensible claim; two relevant details with locations; explanation connects details to the claim.</td></tr><tr><td>Collaboration</td><td>Builds on or tests a peer's idea respectfully; helps others participate using the agreed norms.</td></tr><tr><td>Reflection / transfer</td><td>Identifies what clarified or changed thinking and chooses a specific next step.</td></tr></table>
<p><b>Feedback example:</b> “You located two details. Next, explain why the traveler's tighter grip challenges the Wind's idea of strength.” <b>Practice response:</b> Gentle influence can work where force fails: in ¶2 stronger gusts make the traveler grip the cloak; in ¶3 warmth leads him to remove it. Another reading is that success depends on the task, not absolute strength. Accept different supported claims; do not require one moral.</p>
<h2>Common problems → practical repairs</h2><p><b>Unfinished reading:</b> provide supported in-class catch-up and adjust chunk size. <b>One voice dominates:</b> use a brief round, then open discussion. <b>Silence:</b> silent notes, partner rehearsal, then reread. <b>Unsupported opinions:</b> ask for a location and explanation. <b>Confusion:</b> model one repair strategy and check again. <b>Off-task conflict:</b> restate the norm; conference or regroup when needed.</p>
<p><b>Access:</b> honor IEP/504 and language supports. Offer audio with text, larger print, vocabulary preview, bilingual notes, speech-to-text or an oral exit response. Keep the interpretive goal. Do not equate speech volume or speed with understanding. After two meetings, review student evidence and revise supports, pacing, or grouping.</p>
<h2>Sources, scope, and reuse</h2><p class="small">Official TEKS: <a href="https://tea.texas.gov/laws-and-rules/texas-administrative-code/19-tac-chapter-110">TEA Chapter 110</a> (tea.texas.gov → Laws and Rules → Chapter 110), <a href="https://tea.texas.gov/laws-and-rules/sboe-rules-tac/sboe-tac-currently-effect/ch110a.pdf">Subchapter A</a>, <a href="https://tea.texas.gov/laws-and-rules/sboe-rules-tac/sboe-tac-currently-effect/ch110b.pdf">B</a>, and <a href="https://tea.texas.gov/laws-and-rules/sboe-rules-tac/sboe-tac-currently-effect/ch110c.pdf">C</a>; verified Sept. 16, 2026.<br>Fable source: <a href="https://www.gutenberg.org/ebooks/19994">Project Gutenberg #19994</a>, <i>The Aesop for Children</i> (1919), public domain in the USA.<br>Strategy references: Visible Learning MetaX, <a href="https://www.visiblelearningmetax.com/influences/view/reciprocal_teaching">Reciprocal teaching</a> and <a href="https://www.visiblelearningmetax.com/influences/view/jigsaw_method">Jigsaw method</a> (visiblelearningmetax.com → Influences). The classroom routines here are adaptations; research averages do not guarantee a particular class outcome.</p>
<p class="small">Planning references: the four PDFs in the local litcircles folder (College Board implementation guidance and role-sheet/checklist packets credited to their original providers). This kit uses original wording and layouts; no reference worksheet or artwork is reproduced. Not affiliated with TEA or Visible Learning.<br>© 2026 TCEA · Created by Miguel Guhlin · Kit content CC BY-NC 4.0; code MIT. The underlying Aesop fable remains public domain. Reuse details: mglearn.github.io/printables/licensing.html.</p>
''')
css='''*{box-sizing:border-box}body{margin:0;background:#e8ecef;color:#17232b;font-family:Arial,Helvetica,sans-serif;font-size:11pt;line-height:1.35}.page{position:relative;width:8.5in;height:11in;padding:.48in .55in .5in;background:white;margin:22px auto;break-after:page}.page:last-child{break-after:auto}.eyebrow{font-size:9pt;letter-spacing:1.1px;font-weight:bold;color:#315562;border-bottom:2px solid #315562;padding-bottom:7px}h1{font-size:25pt;line-height:1.05;margin:13px 0}h2{font-size:13pt;margin:13px 0 5px;color:#234957}p{margin:7px 0}.lead{font-size:13pt}.callout{border:1px solid #506973;border-left:5px solid #315562;background:#f3f6f7;padding:9px;margin:10px 0}ul{margin:6px 0;padding-left:21px}li{margin-bottom:6px}table{border-collapse:collapse;width:100%;margin:9px 0;font-size:10pt}td,th{border:1px solid #87969d;text-align:left;vertical-align:top;padding:7px}th{background:#eef2f3}.small{font-size:9pt;line-height:1.32}.write td{height:36px}.write .tall td{height:80px}.lines{background:repeating-linear-gradient(to bottom,transparent 0,transparent 23px,#94a0a5 23px,#94a0a5 24px);margin:3px 0 8px}.two{height:48px}.three{height:72px}.four{height:96px}.reading{border:1px solid #87969d;padding:7px 12px;font-size:11pt}a{color:#234957}footer{position:absolute;bottom:.24in;left:.55in;right:.55in;font-size:8pt;border-top:1px solid #b2bdc2;padding-top:6px;display:flex;justify-content:space-between}.toolbar{max-width:8.5in;margin:20px auto;padding:14px;background:white}.toolbar a,.toolbar button{margin-right:12px;font-size:15px}.checks{list-style:none;padding-left:0}@page{size:letter;margin:0}@media print{body{background:white}.page{margin:0}.toolbar{display:none}a{text-decoration:none;color:inherit}}@media screen and (max-width:850px){.page{width:100%;height:auto;min-height:11in;margin:15px 0;padding:28px 22px 60px}.toolbar{margin:10px}footer{left:22px;right:22px}table{font-size:9pt}}'''
css += '#page-5,#page-6{font-size:10pt}#page-5 .write td{height:28px}#page-5 h2,#page-6 h2{margin-top:10px}#page-6 .two{height:36px}#page-6 .three{height:54px}#page-6 .lines{background:repeating-linear-gradient(to bottom,transparent 0,transparent 17px,#94a0a5 17px,#94a0a5 18px)}#page-6 .write td{height:32px}'
(ROOT/'packet.css').write_text(css)
sections=''.join(f'<section class="page" id="page-{i}"><div class="eyebrow">LITERATURE CIRCLES / {aud}</div><h1>{title}</h1>{body}<footer><span>mglearn · Teacher Printables · Grades 5–12</span><span>{i} / 10</span></footer></section>' for i,(title,aud,body) in enumerate(pages,1))
(ROOT/'packet.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Literature Circles — 10-page Launch Kit</title><link rel="stylesheet" href="packet.css"></head><body><nav class="toolbar" aria-label="Packet actions"><a href="index.html">Collection</a><a href="literature-circles-launch-kit.pdf" download>Download PDF</a><button onclick="window.print()">Print 10 pages</button><p>US Letter · Print at 100% · Single-sided recommended for reusable handouts</p></nav>'+sections+'</body></html>')
items=''.join(f'<li><a href="packet.html#page-{i}">{i}. {escape(t)}</a> <small>— {escape(a.split(" • ")[0].title())}</small></li>' for i,(t,a,b) in enumerate(pages,1))
(ROOT/'index.html').write_text('''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Literature Circles Launch Kit | Teacher Printables</title><meta name="description" content="Free 10-page literature circle organization kit for grades 5–12: teacher setup, local text approval, TEKS, schedules, student handouts, and Aesop practice."><style>body{margin:0;background:#eef2f3;color:#17232b;font:17px/1.6 system-ui,sans-serif}main{max-width:900px;margin:40px auto;padding:30px;background:white;border-top:8px solid #315562}h1{font-size:clamp(2rem,5vw,3rem);line-height:1.15}a{color:#234957}.button{display:inline-block;padding:12px 18px;background:#234957;color:white;border-radius:5px;margin:0 8px 10px 0}li{margin:6px 0}small{color:#52646c}@media(max-width:600px){main{margin:0;padding:24px}}</style><script src="../licensing-footer.js" defer></script></head><body><main><a href="../index.html">← Teacher Printables</a><p>GRADES 5–12 · TEXAS ELAR · 10 PAGES</p><h1>Launch literature circles with a clear plan.</h1><p>A grab-and-go organization kit: choose a locally approved reading, form groups, schedule meetings, teach discussion routines, and check individual understanding.</p><a class="button" href="literature-circles-launch-kit.pdf" download>Download the 10-page PDF</a><a class="button" href="packet.html">Read, adapt, or print online</a><p>Includes a complete Aesop practice reading, reusable student handouts, a grade/course TEKS map, and teacher guidance. Reciprocal Teaching supports comprehension; an optional Jigsaw adds expert lenses when the class is ready.</p><h2>Inside the packet</h2><ol style="list-style:none;padding:0">'''+items+'''</ol><h2>Copy only what you need</h2><p>Teacher: pages 1–4 and 10. Each group: pages 5 and 8. Each student: pages 6, 7, and 9. Print US Letter at 100%; single-sided copies make the forms easy to reuse.</p><h2>Text selection</h2><p>Candidate titles are suggestions for local review. School/district approval must be recorded before launch. The example is an original classroom retelling of “The North Wind and the Sun,” based on Aesop's public-domain fable; older students use it to practice analysis before transferring to a more complex reading.</p><p><a href="README.md">Sources, editable files, and build instructions</a> · <a href="https://github.com/mglearn/printables">mglearn/printables on GitHub</a></p></main></body></html>''')
(ROOT/'README.md').write_text('''# Literature Circles Launch Kit (Grades 5–12)

Ten US Letter pages, with teacher organization guidance and reusable student forms. The original kit draws on the four planning/role PDFs in the sibling reference folder, without reproducing their content or artwork.

- `literature-circles-launch-kit.pdf`: print-ready, exactly 10 pages.
- `packet.html` and `packet.css`: editable, accessible text-based source and print view.
- `index.html`: collection landing page.
- `build.py`: original authoring content and static-page generator (Python standard library).

Run `python3 build.py` to regenerate HTML/CSS. Render `packet.html` with headless Chrome using `--print-to-pdf=literature-circles-launch-kit.pdf --no-pdf-header-footer`. Use US Letter, 100% scale, and no browser headers/footers. Recheck page count and layout after edits.

Copy teacher pp. 1–4 and 10 once, pp. 5 and 8 per group, pp. 6, 7 and 9 per student. The included fable is launch practice for all bands, with increasing analysis demands, rather than a replacement for grade-appropriate sustained reading.

TEKS checked September 16, 2026: https://tea.texas.gov/laws-and-rules/texas-administrative-code/19-tac-chapter-110 (Subchapters A, B, C). High school uses English I–IV course enrollment. Codes and evidence are planning guidance, not a claim that using circles covers every standard.

Public-domain example: https://www.gutenberg.org/ebooks/19994 — The Aesop for Children (1919), public domain in the USA. The included reading is an original retelling with paragraph numbers. Candidate text bands are teacher-review suggestions; no school or state approval is asserted. Exact editions require local review and rights checks.

Strategy references: https://www.visiblelearningmetax.com/influences/view/reciprocal_teaching and https://www.visiblelearningmetax.com/influences/view/jigsaw_method. Routines are classroom adaptations; no outcome guarantee or affiliation is claimed.

Repository/site: https://github.com/mglearn/printables / https://mglearn.github.io/printables/litcircles/

© 2026 TCEA, created by Miguel Guhlin. Original kit content CC BY-NC 4.0; code MIT, consistent with ../licensing.html. The underlying public-domain fable retains that status.
''')
print('Built',len(pages),'pages')
