#!/usr/bin/env bash
# Regenerates assets/sa-manifest.js from the curated CATALOG below (titles, group,
# and blurb come from the intended artwork, not the filename). Add a row when you
# plan/drop in a new sheet. Run from printables/supplemental_aids_elem_math/.
#
# Skips any CATALOG row whose PNG isn't on disk yet, so the gallery only ever shows
# sheets that exist (safe to deploy while images are still being generated). .pdf and
# _packet.pdf links are added only once those files exist.
#
# Groups map to the four Grade 3–5 Math STAAR reporting categories.
set -euo pipefail
cd "$(dirname "$0")"

# base|group|title|blurb
read -r -d '' CATALOG <<'ROWS' || true
em_overview|Start here|Grades 3–5 Math — Overview|A one-page map of the collection: the four STAAR math reporting categories and the cue cards inside each.
em_place_value|Numbers & Fractions|Place Value|Each place is ten times the one to its right — read and write whole numbers and decimals through the thousandths.
em_rounding|Numbers & Fractions|Rounding Numbers|Find the place, look at the digit to its right — 5 or more rounds up, 4 or less stays the same.
em_compare_order|Numbers & Fractions|Comparing & Ordering Numbers|Line up place values and compare from the left; use >, <, and = to order whole numbers and decimals.
em_decimals|Numbers & Fractions|Decimals & Place Value|Tenths, hundredths, and thousandths — a decimal names part of a whole, like money and measurement.
em_fractions_intro|Numbers & Fractions|Understanding Fractions|The numerator counts the parts; the denominator says how many equal parts make the whole.
em_equivalent_fractions|Numbers & Fractions|Equivalent Fractions|Multiply or divide the top and bottom by the same number to name the same amount a different way.
em_compare_fractions|Numbers & Fractions|Comparing Fractions|Same denominator? Compare numerators. Same numerator? Fewer parts are bigger. Or use a common denominator.
em_fractions_decimals|Numbers & Fractions|Fractions & Decimals|Two names for the same value — a number line and place-value chart connect 1/2, 0.5, and 5/10.
em_addition_subtraction|Operations & Algebra|Multi-Digit Addition & Subtraction|Line up place values, add or subtract from the right, and regroup (carry or borrow) when needed.
em_multiplication|Operations & Algebra|Multiplication|Equal groups and arrays — the area model and the standard algorithm for multi-digit products.
em_division|Operations & Algebra|Division|Sharing into equal groups — how the dividend, divisor, quotient, and remainder fit together.
em_fraction_add_sub|Operations & Algebra|Adding & Subtracting Fractions|With a common denominator, add or subtract the numerators and keep the denominator the same.
em_number_patterns|Operations & Algebra|Number Patterns & Tables|Find the rule in an input-output table, then extend the pattern and describe it in words.
em_expressions_equations|Operations & Algebra|Expressions & Equations|Order of operations for grouping symbols, and using a letter or box to stand for an unknown value.
em_2d_shapes|Geometry & Measurement|2D Shapes & Attributes|Classify polygons by sides and angles — triangles, quadrilaterals, and the family tree of shapes.
em_3d_shapes|Geometry & Measurement|3D Solids|Faces, edges, and vertices of cubes, prisms, pyramids, cylinders, cones, and spheres.
em_perimeter_area|Geometry & Measurement|Perimeter & Area|Perimeter is the distance around; area is the square units inside — A = l × w for rectangles.
em_volume|Geometry & Measurement|Volume|Fill a solid with unit cubes — count the cubes, or use V = l × w × h for a rectangular prism.
em_measurement_units|Geometry & Measurement|Measurement Units|Customary and metric length, weight/mass, and capacity — and how to convert within a system.
em_elapsed_time|Geometry & Measurement|Telling & Elapsed Time|Read a clock to the minute and count forward on a number line to find how much time has passed.
em_angles_lines|Geometry & Measurement|Lines & Angles|Points, lines, rays, and segments; parallel and perpendicular lines; right, acute, and obtuse angles.
em_coordinate_grid|Geometry & Measurement|The Coordinate Grid|Plot ordered pairs (x, y) in the first quadrant — over on the x-axis, then up on the y-axis.
em_graphs|Data & Financial Literacy|Reading Graphs|Pull information from bar graphs, pictographs, dot plots, and frequency tables to answer questions.
em_data_tables|Data & Financial Literacy|Frequency Tables & Dot Plots|Organize data into tallies and tables, then show it on a dot plot and read the shape of the data.
em_financial_literacy|Data & Financial Literacy|Money & Financial Literacy|Count money and make change; the difference between saving and spending, income, and a simple budget.
ROWS

esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

out=assets/sa-manifest.js
n=0; missing=0
{
  echo "/* AUTO-GENERATED by build-manifest.sh — do not edit by hand. */"
  echo "window.EM_MANIFEST = ["
  while IFS='|' read -r base group title blurb; do
    [ -n "$base" ] || continue
    png="${base}.png"
    [ -f "$png" ] || { echo "NOTE: $png not generated yet (row skipped)." >&2; missing=$((missing+1)); continue; }
    pdf="${base}.pdf";        pdfval="";    [ -f "$pdf" ]    && pdfval="$pdf"
    packet="${base}_packet.pdf"; packetval=""; [ -f "$packet" ] && packetval="$packet"
    printf '  { "strand": "%s", "title": "%s", "blurb": "%s", "file": "%s", "pdf": "%s", "packet": "%s" },\n' \
      "$(esc "$group")" "$(esc "$title")" "$(esc "$blurb")" "$png" "$pdfval" "$packetval"
    n=$((n+1))
  done <<< "$CATALOG"
  echo "];"
} > "$out"

for png in em_*.png; do
  [ -e "$png" ] || continue
  base="${png%.png}"
  grep -q "^${base}|" <<< "$CATALOG" || echo "NOTE: $png is on disk but not in CATALOG (add a row)." >&2
done

echo "Wrote $out ($n entries, $missing image(s) not yet generated)"
