#!/usr/bin/env python3
"""
Generate compliance-matrix.md (section 16) and the teacher catalog data file
from tools/aids.json. Reproducible; no network, no timestamps baked into logic
(the review date is passed in as a constant below and mirrored in the docs).
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
REVIEW_DATE = "2026-09-25"          # single place to update the review date

data = json.load(open(os.path.join(HERE, "aids.json")))
aids = data["aids"]
classroom = data["classroom_only"]


# ---- compliance-matrix.md ---------------------------------------------------
def matrix():
    out = []
    out.append("# Teacher Compliance Matrix\n")
    out.append("Per spec section 16. Status values: `CANDIDATE`, "
               "`CLASSROOM USE ONLY`, `NEEDS TEA/LOCAL VERIFICATION`, `RETIRED`, "
               "`LOCAL REVIEW COMPLETE`. The value `TEA APPROVED` is never used.\n")
    out.append(f"**Official source checked:** see `sources/tea-source-log.md` and "
               f"`sources/reference-material-log.md` · **Review date:** {REVIEW_DATE} "
               f"· **Testing year:** 2025-2026\n")
    out.append("> Designed to follow current TEA supplemental-aid guidance. Final "
               "student eligibility and use remain subject to current TEA "
               "requirements and local testing procedures.\n")
    out.append("## Candidate aids\n")
    hdr = ("| Existing Resource | Subject | Grade/Course | TEA Aid Type | Candidate? "
           "| Changes Required | Official Source Checked | Review Date | Local Review |")
    sep = "|---|---|---|---|---|---|---|---|---|"
    out.append(hdr)
    out.append(sep)
    for a in aids:
        out.append("| {src} | {subj} | {grade} | `{typ}` | {status} | {notes} "
                   "| tea-source-log.md | {rev} | required |".format(
                       src=a["source"], subj=a["subject"], grade=a["grade"],
                       typ=a["aid_type"], status=a["status"],
                       notes=a["notes"], rev=REVIEW_DATE))
    out.append("\n## Classroom-use-only determinations (not built as candidates)\n")
    out.append("| Existing Resource | Subject | TEA Aid Type | Candidate? | Reason |")
    out.append("|---|---|---|---|---|")
    for c in classroom:
        out.append("| {src} | {subj} | (none) | CLASSROOM USE ONLY | {reason} |".format(
            src=c["source"], subj=c["subject"], reason=c["reason"]))
    out.append("")
    return "\n".join(out)


# ---- catalog-data.js -------------------------------------------------------
def catalog_js():
    rows = []
    for a in aids:
        rel = a["path"]                 # paths are relative to the saguides/ root
        rows.append({
            "title": a["concept"],
            "subject": a["subject"],
            "grade": a["grade"],
            "aid_type": a["aid_type"],
            "teks": a["teks"],
            "cue": a["cue"],
            "status": a["status"],
            "notes": a["notes"],
            "png": rel.replace(".svg", ".png"),
            "pdf": rel.replace(".svg", ".pdf"),
            "svg": rel,
        })
    payload = {"reviewDate": REVIEW_DATE, "aids": rows,
               "classroomOnly": classroom}
    return "/* AUTO-GENERATED by tools/build_catalog.py — do not edit by hand. */\n" \
           "window.SACL = " + json.dumps(payload, indent=2) + ";\n"


with open(os.path.join(ROOT, "compliance-matrix.md"), "w") as f:
    f.write(matrix())
with open(os.path.join(ROOT, "catalog-data.js"), "w") as f:
    f.write(catalog_js())
print(f"compliance-matrix.md: {len(aids)} candidates, {len(classroom)} classroom-only")
print("catalog-data.js written")
