#!/usr/bin/env bash
# Regenerates assets/pcs-manifest.js by scanning the Phase Change station PNGs in
# this folder. Titles, the phase-change transition, and the focus question are
# curated here (they come from the artwork, not the filename), so add a row to
# CATALOG when you drop in a new station. Run from tgt/phase_change_stations/.
set -euo pipefail
cd "$(dirname "$0")"

# base|station|transition|title|focus
# order below is also the gallery display order (the lab runs 1 -> 7).
read -r -d '' CATALOG <<'ROWS' || true
pcs_station1_melting_ice|1|Solid → liquid (melting)|Melting Ice|What evidence shows energy entered the system, and what happened to the particles?
pcs_station2_condensation|2|Gas → liquid (condensation)|Where Did the Water Come From?|How do droplets form on the outside of a cold cup?
pcs_station3_race_to_evaporate|3|Liquid → gas (evaporation)|Race to Evaporate|Which conditions make water evaporate faster?
pcs_station4_make_frost|4|Gas → solid (deposition)|Make Frost|How can water vapor change directly into a solid?
pcs_station5_melt_it_freeze_it|5|Solid ↔ liquid (reversible)|Melt It, Freeze It|How can a substance melt and then solidify again?
pcs_station6_particle_detective|6|Particle modeling (all changes)|Particle Detective|What do particle models reveal about phase change?
pcs_station7_dry_ice_sublimation|7|Solid → gas (sublimation)|Dry Ice Sublimation (Teacher Demo)|How can a solid change directly into a gas?
ROWS

esc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'; }

out=assets/pcs-manifest.js
n=0
{
  echo "/* AUTO-GENERATED by build-manifest.sh — do not edit by hand. */"
  echo "window.PCS_MANIFEST = ["
  while IFS='|' read -r base station transition title focus; do
    [ -n "$base" ] || continue
    png="${base}.png"
    if [ ! -f "$png" ]; then
      echo "  WARNING: $png listed in CATALOG but not found on disk" >&2
      continue
    fi
    pdf="${base}.pdf"
    pdfval=""
    [ -f "$pdf" ] && pdfval="$pdf"
    printf '  { "station": "%s", "transition": "%s", "title": "%s", "focus": "%s", "file": "%s", "pdf": "%s" },\n' \
      "$(esc "$station")" "$(esc "$transition")" "$(esc "$title")" "$(esc "$focus")" "$png" "$pdfval"
    n=$((n+1))
  done <<< "$CATALOG"
  echo "];"
} > "$out"

# Flag any PNG on disk that is missing from the CATALOG.
for png in pcs_*.png; do
  [ -e "$png" ] || continue
  base="${png%.png}"
  grep -q "^${base}|" <<< "$CATALOG" || echo "NOTE: $png is on disk but not in CATALOG (add a row)." >&2
done

echo "Wrote $out ($n entries)"
