/* Teacher catalog renderer for the STAAR Supplemental Aid Candidate Library.
   Reads window.SACL (generated by tools/build_catalog.py). Pure client-side.
   This catalog is a TEACHER REFERENCE — it is not a student testing aid. */
(function () {
  'use strict';
  var D = window.SACL || { aids: [], classroomOnly: [], reviewDate: '' };

  function el(t, c, txt) { var e = document.createElement(t); if (c) e.className = c; if (txt != null) e.textContent = txt; return e; }
  function uniq(arr) { return arr.filter(function (v, i) { return arr.indexOf(v) === i; }).sort(); }

  function badgeClass(status) {
    if (status === 'CANDIDATE') return 'badge candidate';
    if (status.indexOf('VERIFICATION') > -1) return 'badge verify';
    return 'badge classroom';
  }

  function fill(sel, values) {
    var s = document.getElementById(sel);
    values.forEach(function (v) { var o = el('option', null, v); o.value = v; s.appendChild(o); });
  }

  function card(a) {
    var c = el('div', 'sacl-card');
    var th = el('div', 'sacl-thumb');
    var img = el('img'); img.loading = 'lazy'; img.src = a.png; img.alt = a.title + ' (unlabeled candidate preview)';
    th.appendChild(img); c.appendChild(th);
    var b = el('div', 'sacl-body');
    b.appendChild(el('div', 'sacl-title', a.title));
    var meta = el('div', 'sacl-meta'); meta.textContent = a.subject + ' · Grade ' + a.grade + ' · TEKS: ' + a.teks;
    b.appendChild(meta);
    var row = el('div'); row.style.display = 'flex'; row.style.gap = '.4rem'; row.style.flexWrap = 'wrap';
    row.appendChild(el('span', 'sacl-type', a.aid_type));
    // "CANDIDATE" is the default state (explained in the status key at the page
    // bottom); only surface the exceptions per-card.
    if (a.status !== 'CANDIDATE') row.appendChild(el('span', badgeClass(a.status), a.status));
    b.appendChild(row);
    b.appendChild(el('div', 'sacl-cue', 'Memory cue: ' + a.cue));
    b.appendChild(el('div', 'sacl-notes', a.notes));
    var dls = el('div', 'sacl-dls');
    ['pdf', 'png', 'svg'].forEach(function (k) {
      var link = el('a', null, k.toUpperCase()); link.href = a[k]; link.setAttribute('download', ''); dls.appendChild(link);
    });
    b.appendChild(dls);
    var rv = el('label', 'sacl-review');
    var cb = el('input'); cb.type = 'checkbox';
    rv.appendChild(cb); rv.appendChild(document.createTextNode(' Local review complete'));
    b.appendChild(rv);
    c.appendChild(b);
    return c;
  }

  function render() {
    var subj = document.getElementById('f-subject').value;
    var typ = document.getElementById('f-type').value;
    var st = document.getElementById('f-status').value;
    var grid = document.getElementById('grid'); grid.innerHTML = '';
    var shown = D.aids.filter(function (a) {
      return (!subj || a.subject === subj) && (!typ || a.aid_type === typ) && (!st || a.status === st);
    });
    shown.forEach(function (a) { grid.appendChild(card(a)); });
    document.getElementById('count').textContent = shown.length + ' of ' + D.aids.length + ' aids';
  }

  function init() {
    document.getElementById('review-date').textContent = D.reviewDate || '—';
    fill('f-subject', uniq(D.aids.map(function (a) { return a.subject; })));
    fill('f-type', uniq(D.aids.map(function (a) { return a.aid_type; })));
    fill('f-status', uniq(D.aids.map(function (a) { return a.status; })));
    ['f-subject', 'f-type', 'f-status'].forEach(function (id) {
      document.getElementById(id).addEventListener('change', render);
    });
    render();
    var co = document.getElementById('co-list');
    (D.classroomOnly || []).forEach(function (c) {
      co.appendChild(el('li', null, c.source + ' — ' + c.reason));
    });
  }

  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', init);
  else init();
})();
