/* AUTO-GENERATED by tools/build_catalog.py — do not edit by hand. */
window.SACL = {
  "reviewDate": "2026-09-25",
  "aids": [
    {
      "title": "Hundreds chart (1-100)",
      "subject": "Math",
      "grade": "3-5",
      "aid_type": "math_number_chart",
      "teks": "counting, patterns, number relationships",
      "cue": "Recall counting/skip-count patterns",
      "status": "CANDIDATE",
      "notes": "Plain chart; no highlighting/shading.",
      "png": "candidates/math/grade-3/math-g3_5-number-chart-100.png",
      "pdf": "candidates/math/grade-3/math-g3_5-number-chart-100.pdf",
      "svg": "candidates/math/grade-3/math-g3_5-number-chart-100.svg"
    },
    {
      "title": "Blank whole-number place-value chart",
      "subject": "Math",
      "grade": "3-5",
      "aid_type": "math_place_value_chart",
      "teks": "place value to millions",
      "cue": "Align digits by place",
      "status": "CANDIDATE",
      "notes": "Blank cells + period commas only; no words/examples.",
      "png": "candidates/math/grade-4/math-g3_5-place-value-whole-blank.png",
      "pdf": "candidates/math/grade-4/math-g3_5-place-value-whole-blank.pdf",
      "svg": "candidates/math/grade-4/math-g3_5-place-value-whole-blank.svg"
    },
    {
      "title": "Blank decimal place-value chart",
      "subject": "Math",
      "grade": "5",
      "aid_type": "math_place_value_chart",
      "teks": "decimals to thousandths",
      "cue": "Align digits around the decimal point",
      "status": "CANDIDATE",
      "notes": "Blank cells + decimal point only.",
      "png": "candidates/math/grade-5/math-g5-place-value-decimal-blank.png",
      "pdf": "candidates/math/grade-5/math-g5-place-value-decimal-blank.pdf",
      "svg": "candidates/math/grade-5/math-g5-place-value-decimal-blank.svg"
    },
    {
      "title": "Unlabeled fraction bars (wall)",
      "subject": "Math",
      "grade": "3-5",
      "aid_type": "math_fraction_model",
      "teks": "fractions, equivalence",
      "cue": "Compare partition sizes",
      "status": "CANDIDATE",
      "notes": "Partitioning only; no numbers/labels/equivalency.",
      "png": "candidates/math/grade-3/math-g3_5-fraction-bars-blank.png",
      "pdf": "candidates/math/grade-3/math-g3_5-fraction-bars-blank.pdf",
      "svg": "candidates/math/grade-3/math-g3_5-fraction-bars-blank.svg"
    },
    {
      "title": "Unlabeled fraction circles",
      "subject": "Math",
      "grade": "3-5",
      "aid_type": "math_fraction_model",
      "teks": "fractions, equivalence",
      "cue": "See equal partitions of a whole",
      "status": "CANDIDATE",
      "notes": "Partitioning only; no numbers/labels.",
      "png": "candidates/math/grade-3/math-g3_5-fraction-circles-blank.png",
      "pdf": "candidates/math/grade-3/math-g3_5-fraction-circles-blank.pdf",
      "svg": "candidates/math/grade-3/math-g3_5-fraction-circles-blank.svg"
    },
    {
      "title": "Basic 2-D geometric figures",
      "subject": "Math",
      "grade": "3-5",
      "aid_type": "math_geometry_2d",
      "teks": "classify 2-D figures",
      "cue": "Recall figure shapes",
      "status": "CANDIDATE",
      "notes": "Outlines only; no names/measures. Keep 2-D and 3-D separate (\u00a76D).",
      "png": "candidates/math/grade-3/math-g3-2d-figures.png",
      "pdf": "candidates/math/grade-3/math-g3-2d-figures.pdf",
      "svg": "candidates/math/grade-3/math-g3-2d-figures.svg"
    },
    {
      "title": "Expanded 2-D geometric figures",
      "subject": "Math",
      "grade": "5-7",
      "aid_type": "math_geometry_2d",
      "teks": "classify triangles/quadrilaterals/polygons",
      "cue": "Recall figure shapes",
      "status": "CANDIDATE",
      "notes": "Outlines only; no names/measures/angles.",
      "png": "candidates/math/grade-5/math-g5_7-2d-figures.png",
      "pdf": "candidates/math/grade-5/math-g5_7-2d-figures.pdf",
      "svg": "candidates/math/grade-5/math-g5_7-2d-figures.svg"
    },
    {
      "title": "3-D geometric solids",
      "subject": "Math",
      "grade": "6-8",
      "aid_type": "math_geometry_3d",
      "teks": "3-D figures, nets/volume context",
      "cue": "Recall solid shapes",
      "status": "CANDIDATE",
      "notes": "Solids only (no nets); no labels/measures. Separate from 2-D (\u00a76D).",
      "png": "candidates/math/grade-6/math-g6_8-3d-figures.png",
      "pdf": "candidates/math/grade-6/math-g6_8-3d-figures.pdf",
      "svg": "candidates/math/grade-6/math-g6_8-3d-figures.svg"
    },
    {
      "title": "Order-of-operations acronym",
      "subject": "Math",
      "grade": "5-8",
      "aid_type": "mnemonic",
      "teks": "order of operations",
      "cue": "Recall the operation order",
      "status": "NEEDS TEA/LOCAL VERIFICATION",
      "notes": "Acronym letters only; no decoded words/symbols (\u00a75). Local review: confirm acronym mnemonics are accepted.",
      "png": "candidates/math/mnemonics/math-g6-mnemonic-pemdas.png",
      "pdf": "candidates/math/mnemonics/math-g6-mnemonic-pemdas.pdf",
      "svg": "candidates/math/mnemonics/math-g6-mnemonic-pemdas.svg"
    },
    {
      "title": "Blank Venn diagram",
      "subject": "Math/Science",
      "grade": "3-8",
      "aid_type": "blank_graphic_organizer",
      "teks": "compare/contrast, sort",
      "cue": "Sort into overlapping sets",
      "status": "CANDIDATE",
      "notes": "Genuinely blank; no words/labels/numbers.",
      "png": "candidates/math/blank-organizers/math-venn-blank.png",
      "pdf": "candidates/math/blank-organizers/math-venn-blank.pdf",
      "svg": "candidates/math/blank-organizers/math-venn-blank.svg"
    },
    {
      "title": "Blank T-chart",
      "subject": "Math/Science",
      "grade": "3-8",
      "aid_type": "blank_graphic_organizer",
      "teks": "organize pairs/relationships",
      "cue": "Two-column structure",
      "status": "CANDIDATE",
      "notes": "Genuinely blank; no words/labels/numbers.",
      "png": "candidates/math/blank-organizers/math-tchart-blank.png",
      "pdf": "candidates/math/blank-organizers/math-tchart-blank.pdf",
      "svg": "candidates/math/blank-organizers/math-tchart-blank.svg"
    },
    {
      "title": "Blank four-quadrant organizer",
      "subject": "Math/Science",
      "grade": "3-8",
      "aid_type": "blank_graphic_organizer",
      "teks": "organize a concept",
      "cue": "Four-part structure",
      "status": "CANDIDATE",
      "notes": "Genuinely blank; no words/labels/numbers.",
      "png": "candidates/math/blank-organizers/math-frayer-blank.png",
      "pdf": "candidates/math/blank-organizers/math-frayer-blank.pdf",
      "svg": "candidates/math/blank-organizers/math-frayer-blank.svg"
    },
    {
      "title": "Blank table grid",
      "subject": "Math/Science",
      "grade": "3-8",
      "aid_type": "blank_graphic_organizer",
      "teks": "organize data",
      "cue": "Rows/columns structure",
      "status": "CANDIDATE",
      "notes": "Genuinely blank; no words/labels/numbers.",
      "png": "candidates/math/blank-organizers/math-grid-blank.png",
      "pdf": "candidates/math/blank-organizers/math-grid-blank.pdf",
      "svg": "candidates/math/blank-organizers/math-grid-blank.svg"
    },
    {
      "title": "States of matter (particle spacing)",
      "subject": "Science",
      "grade": "5-8",
      "aid_type": "science_graphic",
      "teks": "particle model of solids/liquids/gases",
      "cue": "Recall particle spacing/arrangement",
      "status": "CANDIDATE",
      "notes": "Grayscale particles; no labels/arrows/color-coding.",
      "png": "candidates/science/grade-8/science-g5_8-states-of-matter-unlabeled.png",
      "pdf": "candidates/science/grade-8/science-g5_8-states-of-matter-unlabeled.pdf",
      "svg": "candidates/science/grade-8/science-g5_8-states-of-matter-unlabeled.svg"
    },
    {
      "title": "Element / compound / mixture particles",
      "subject": "Science",
      "grade": "8",
      "aid_type": "science_graphic",
      "teks": "classification of matter",
      "cue": "Distinguish particle groupings",
      "status": "CANDIDATE",
      "notes": "Grayscale particles; no labels/arrows/color.",
      "png": "candidates/science/grade-8/science-g8-element-compound-mixture-unlabeled.png",
      "pdf": "candidates/science/grade-8/science-g8-element-compound-mixture-unlabeled.pdf",
      "svg": "candidates/science/grade-8/science-g8-element-compound-mixture-unlabeled.svg"
    },
    {
      "title": "Mixture (two particle types)",
      "subject": "Science",
      "grade": "5",
      "aid_type": "science_graphic",
      "teks": "mixtures keep their properties",
      "cue": "Two materials mixed, not bonded",
      "status": "CANDIDATE",
      "notes": "Two neutral shapes; no labels/color.",
      "png": "candidates/science/grade-5/science-g5-mixture-unlabeled.png",
      "pdf": "candidates/science/grade-5/science-g5-mixture-unlabeled.pdf",
      "svg": "candidates/science/grade-5/science-g5-mixture-unlabeled.svg"
    },
    {
      "title": "Atomic structure (generic Bohr model)",
      "subject": "Science",
      "grade": "8",
      "aid_type": "science_graphic",
      "teks": "atomic structure",
      "cue": "Nucleus + electron shells layout",
      "status": "CANDIDATE",
      "notes": "Generic (no element implied); no numbers/labels.",
      "png": "candidates/science/grade-8/science-g8-atomic-structure-unlabeled.png",
      "pdf": "candidates/science/grade-8/science-g8-atomic-structure-unlabeled.pdf",
      "svg": "candidates/science/grade-8/science-g8-atomic-structure-unlabeled.svg"
    },
    {
      "title": "Moon phases (illumination shapes)",
      "subject": "Science",
      "grade": "5-8",
      "aid_type": "science_graphic",
      "teks": "lunar cycle",
      "cue": "Recall the illuminated-shape sequence",
      "status": "NEEDS TEA/LOCAL VERIFICATION",
      "notes": "Shading depicts illumination (not a color label). Local review: confirm grayscale illumination is acceptable; no numbers/arrows/labels.",
      "png": "candidates/science/grade-8/science-g5_8-moon-phases-unlabeled.png",
      "pdf": "candidates/science/grade-8/science-g5_8-moon-phases-unlabeled.pdf",
      "svg": "candidates/science/grade-8/science-g5_8-moon-phases-unlabeled.svg"
    },
    {
      "title": "Plate-boundary cross-sections",
      "subject": "Science",
      "grade": "8",
      "aid_type": "science_graphic",
      "teks": "plate tectonics",
      "cue": "Recall boundary geometry",
      "status": "NEEDS TEA/LOCAL VERIFICATION",
      "notes": "No arrows/labels. Local review: confirm the geometry is unambiguous without motion arrows; otherwise classroom-only.",
      "png": "candidates/science/grade-8/science-g8-plate-boundaries-unlabeled.png",
      "pdf": "candidates/science/grade-8/science-g8-plate-boundaries-unlabeled.pdf",
      "svg": "candidates/science/grade-8/science-g8-plate-boundaries-unlabeled.svg"
    },
    {
      "title": "Animal cell (unlabeled organelles)",
      "subject": "Science",
      "grade": "8/Biology",
      "aid_type": "science_graphic",
      "teks": "cell structure",
      "cue": "Recall organelle shapes/locations",
      "status": "CANDIDATE",
      "notes": "Line art; no labels/color/arrows.",
      "png": "candidates/science/grade-8/science-g8-bio-animal-cell-unlabeled.png",
      "pdf": "candidates/science/grade-8/science-g8-bio-animal-cell-unlabeled.pdf",
      "svg": "candidates/science/grade-8/science-g8-bio-animal-cell-unlabeled.svg"
    },
    {
      "title": "Plant cell (unlabeled organelles)",
      "subject": "Science",
      "grade": "8/Biology",
      "aid_type": "science_graphic",
      "teks": "cell structure",
      "cue": "Recall wall/vacuole/organelle layout",
      "status": "CANDIDATE",
      "notes": "Line art; no labels/color/arrows.",
      "png": "candidates/science/grade-8/science-g8-bio-plant-cell-unlabeled.png",
      "pdf": "candidates/science/grade-8/science-g8-bio-plant-cell-unlabeled.pdf",
      "svg": "candidates/science/grade-8/science-g8-bio-plant-cell-unlabeled.svg"
    },
    {
      "title": "Plant parts (unlabeled)",
      "subject": "Science",
      "grade": "3-5",
      "aid_type": "science_graphic",
      "teks": "plant structures/functions",
      "cue": "Recall roots/stem/leaves/flower",
      "status": "CANDIDATE",
      "notes": "Line art; no labels/color/arrows.",
      "png": "candidates/science/grade-5/science-g5-plant-parts-unlabeled.png",
      "pdf": "candidates/science/grade-5/science-g5-plant-parts-unlabeled.pdf",
      "svg": "candidates/science/grade-5/science-g5-plant-parts-unlabeled.svg"
    },
    {
      "title": "Transverse wave (unlabeled)",
      "subject": "Science",
      "grade": "8",
      "aid_type": "science_graphic",
      "teks": "wave properties",
      "cue": "Recall amplitude/wavelength shape",
      "status": "CANDIDATE",
      "notes": "Curve + faint rest axis; no labels/measures/arrows.",
      "png": "candidates/science/grade-8/science-g8-transverse-wave-unlabeled.png",
      "pdf": "candidates/science/grade-8/science-g8-transverse-wave-unlabeled.pdf",
      "svg": "candidates/science/grade-8/science-g8-transverse-wave-unlabeled.svg"
    },
    {
      "title": "Simple closed circuit (pictorial)",
      "subject": "Science",
      "grade": "4-5",
      "aid_type": "science_graphic",
      "teks": "electricity, closed circuit",
      "cue": "Recall a complete loop",
      "status": "NEEDS TEA/LOCAL VERIFICATION",
      "notes": "Pictorial (not schematic symbols); no text. Local review: confirm pictorial circuit is acceptable; otherwise classroom-only.",
      "png": "candidates/science/grade-5/science-g5-simple-circuit-unlabeled.png",
      "pdf": "candidates/science/grade-5/science-g5-simple-circuit-unlabeled.pdf",
      "svg": "candidates/science/grade-5/science-g5-simple-circuit-unlabeled.svg"
    },
    {
      "title": "Density relationship (variables only)",
      "subject": "Science",
      "grade": "8",
      "aid_type": "science_formula_triangle",
      "teks": "density = mass/volume",
      "cue": "Recall the m/D/V relationship",
      "status": "CANDIDATE",
      "notes": "On G8 science reference sheet. Variables only; no name/units/operators.",
      "png": "candidates/science/grade-8/science-g8-formula-triangle-density.png",
      "pdf": "candidates/science/grade-8/science-g8-formula-triangle-density.pdf",
      "svg": "candidates/science/grade-8/science-g8-formula-triangle-density.svg"
    },
    {
      "title": "Average speed relationship (variables only)",
      "subject": "Science",
      "grade": "8",
      "aid_type": "science_formula_triangle",
      "teks": "speed = distance/time",
      "cue": "Recall the d/s/t relationship",
      "status": "CANDIDATE",
      "notes": "On G8 science reference sheet. Variables only.",
      "png": "candidates/science/grade-8/science-g8-formula-triangle-average-speed.png",
      "pdf": "candidates/science/grade-8/science-g8-formula-triangle-average-speed.pdf",
      "svg": "candidates/science/grade-8/science-g8-formula-triangle-average-speed.svg"
    },
    {
      "title": "Net force relationship (variables only)",
      "subject": "Science",
      "grade": "8",
      "aid_type": "science_formula_triangle",
      "teks": "F = m x a",
      "cue": "Recall the F/m/a relationship",
      "status": "CANDIDATE",
      "notes": "On G8 science reference sheet. Variables only.",
      "png": "candidates/science/grade-8/science-g8-formula-triangle-net-force.png",
      "pdf": "candidates/science/grade-8/science-g8-formula-triangle-net-force.pdf",
      "svg": "candidates/science/grade-8/science-g8-formula-triangle-net-force.svg"
    },
    {
      "title": "Work relationship (variables only)",
      "subject": "Science",
      "grade": "8",
      "aid_type": "science_formula_triangle",
      "teks": "W = F x d",
      "cue": "Recall the W/F/d relationship",
      "status": "CANDIDATE",
      "notes": "On G8 science reference sheet. Variables only.",
      "png": "candidates/science/grade-8/science-g8-formula-triangle-work.png",
      "pdf": "candidates/science/grade-8/science-g8-formula-triangle-work.pdf",
      "svg": "candidates/science/grade-8/science-g8-formula-triangle-work.svg"
    }
  ],
  "classroomOnly": [
    {
      "source": "Science formula triangle: Weight (W=mg)",
      "subject": "Science",
      "reason": "Not on G8 science reference sheet (fail-closed, \u00a710)."
    },
    {
      "source": "Science formula triangle: Momentum (p=mv)",
      "subject": "Science",
      "reason": "Not on G8 science reference sheet."
    },
    {
      "source": "Science formula triangle: Pressure (P=F/A)",
      "subject": "Science",
      "reason": "Not on G8 science reference sheet."
    },
    {
      "source": "Science formula triangle: Power (P=W/t)",
      "subject": "Science",
      "reason": "Not on G8 science reference sheet."
    },
    {
      "source": "Science formula triangle: Wave speed (v=f\u03bb)",
      "subject": "Science",
      "reason": "Not on G8 science reference sheet."
    },
    {
      "source": "Science formula triangle: Ohm's law (V=IR)",
      "subject": "Science",
      "reason": "Not on G8 science reference sheet."
    },
    {
      "source": "Water cycle diagram",
      "subject": "Science",
      "reason": "Meaning depends on arrows/labels; ambiguous when stripped (\u00a79)."
    },
    {
      "source": "Rock cycle diagram",
      "subject": "Science",
      "reason": "Cyclic process needs arrows/labels (\u00a79)."
    },
    {
      "source": "Weathering/erosion/deposition",
      "subject": "Science",
      "reason": "Process meaning depends on arrows/labels."
    },
    {
      "source": "Life cycles",
      "subject": "Science",
      "reason": "Sequence meaning depends on arrows/order."
    },
    {
      "source": "Food chains / food webs",
      "subject": "Science",
      "reason": "Energy-flow arrows are essential (\u00a79)."
    },
    {
      "source": "Ecological succession",
      "subject": "Science",
      "reason": "Time-sequence meaning depends on order/labels."
    },
    {
      "source": "Heat transfer (conduction/convection/radiation)",
      "subject": "Science",
      "reason": "Distinctions depend on arrows/labels."
    },
    {
      "source": "Electromagnetic spectrum",
      "subject": "Science",
      "reason": "Meaning depends on labels/scale/values."
    },
    {
      "source": "Physical vs chemical change",
      "subject": "Science",
      "reason": "Abstract; requires labels/examples."
    },
    {
      "source": "Photosynthesis",
      "subject": "Science",
      "reason": "Requires chemical formula/labels."
    },
    {
      "source": "Newton's laws / net force diagrams",
      "subject": "Science",
      "reason": "Force arrows/vectors/labels prohibited (\u00a79)."
    },
    {
      "source": "All MATH formula sheets / formula triangles",
      "subject": "Math",
      "reason": "Math formula aids not a permitted category (\u00a77)."
    },
    {
      "source": "Multiplication/operation strategy cards",
      "subject": "Math",
      "reason": "Procedures/strategies not permitted (\u00a77)."
    },
    {
      "source": "Conversion / measurement rule cards",
      "subject": "Math",
      "reason": "Rule/procedure content not permitted (\u00a77)."
    }
  ]
};
